version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  image-classifier-new:
    lang: python3-http-debian
    handler: ./image-classifier-new
    image: rutanshsuthar/image-classifier-new:latest

