apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ml-image-classifier
  namespace: demo
spec:
  template:
    spec:
      containers:
        - image: akshat1304/ml-image-classifier:latest
          ports:
            - containerPort: 8080


# apiVersion: serving.knative.dev/v1
# kind: Service
# metadata:
#   name: ml-image-classifier
#   namespace: demo
# spec:
#   template:
#     metadata:
#       annotations:
#         autoscaling.knative.dev/minScale: "1"  # Ensure minimum of 1 pod
#     spec:
#       containers:
#         - image: akshat1304/ml-image-classifier:latest  # Your image name
#           name: ml-image-classifier
#           ports:
#             - containerPort: 8080
