apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: react-example
  namespace: demo
spec:
  template:
    metadata:
      name: react-example-first
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
        - image: docker.io/anaisurlichs/knative-demo:current
          ports:
          - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: TARGET
              value: "Knative React v1"
  traffic:
  - tag: current
    latestRevision: true
    percent: 100